### ISSUE TITLE
The styles for actions at the bottom of the mail view is broken

### ISSUE THREAD

**Issue by m4heshd** [EvHaus/google-redesigned#199]
<img width="1519" height="115" alt="Image" src="https://github.com/user-attachments/assets/82b4740f-906c-4463-9f84-784706e5921d" />

**Comment by EvHaus** [comment]
Should be fixed in the latest version.

**Comment by m4heshd** [comment]
@EvHaus Thank you for the quick update. Just updated and checked, but the issue is still there. The selector for me is `.nH.btDi4d`. Could it be two different compilations of their CSS? 🤔

**Comment by m4heshd** [comment]
@EvHaus Great. I'll write some overrides for myself in the meantime. Would also love to see this menu darkened.

<img width="217" height="496" alt="Image" src="https://github.com/user-attachments/assets/7deaabb5-1efc-41ab-a47c-fa770a844098" />
